name: ShadowfangReclaimed
version: '${version}'
main: com.shadowfang.core.ShadowfangCorePlugin
api-version: '1.21'
folia-supported: true
description: The master plugin for Shadowfang on Folia.
softdepend: []
commands:
  sr:
    description: Shadowfang Reclaimed command root
    usage: /sr <sub-plugin> <subcommand>
  vm:
    description: Quick toggle veinmining
    usage: /vm
permissions:
  shadowfang.cmd:
    description: Access /sr commands
    default: op
  shadowfang.we.use:
    description: Use the path tools
    default: op
  shadowfang.we.admin:
    description: Admin path tools
    default: op
